#!/bin/bash

#  /$$      /$$           /$$
# | $$  /$ | $$          | $$
# | $$ /$$$| $$  /$$$$$$ | $$  /$$$$$$   /$$$$$$
# | $$/$$ $$ $$ |____  $$| $$ /$$__  $$ /$$__  $$
# | $$$$_  $$$$  /$$$$$$$| $$| $$  \__/| $$  \ $$
# | $$$/ \  $$$ /$$__  $$| $$| $$      | $$  | $$
# | $$/   \  $$|  $$$$$$$| $$| $$      | $$$$$$$/
# |__/     \__/ \_______/|__/|__/      | $$____/
#                                      | $$
#                                      | $$
#                                      |__/      
# 
#
# Made by MaironGui3 ~ v1.0
# Walrp ~> Wal for Rofi and Polybar

dir1="$HOME/.config/polybar/scripts/rofi"
dir2="$HOME/.config/rofi/themes"
file="$HOME/.cache/wal/colors-rofi-dark.rasi"

i=1
while read line; do
echo "$line" >> ~/colors.rasi && cat ~/colors.rasi > /dev/null 2>&1
i=$((i+1))
if [ "$i" -ge 30 ]
then
	xargs -n 1 cp -v ~/colors.rasi<<<"$dir1 $dir2" > /dev/null 2>&1
	rm ~/colors.rasi
	echo "Done... :)"
	break
fi
done < $file

